tuning_id: cloud_tuning_fine

seed: 42
dataset:
  name: cloud
  log10_transform: True
  normalise: minmax
  subset_factor: 1
  tolerance: 1e-25
  normalise_per_species: True
  log_timesteps: True
devices: ["cuda:2", "cuda:3", "cuda:4", "cuda:5", "cuda:6", "cuda:7", "cuda:8", "cuda:9"]
optuna_logs: False
prune: True
verbose: False
multi_objective: True
population_size: 30
target_percentile: 0.99
postgres_config:
  mode: "local"                # "local" or "remote"
  port: 5432
  user: "optuna_user"
  host: "localhost" # "localhost" for local use
  database_folder: "/export/home/rjanssen/postgres/" # only for local use
  db_name: "optuna_cloud_2"       # remote mode: single DB for all runs
  sslmode: "require"            # if needed
  password: ""                # optional; prefer env PGPASSWORD

global_optuna_params:
  learning_rate:
    type: float
    low: 1.0e-6
    high: 1.0e-2
    log: true
  regularization_factor:
    type: float
    low: 1.0e-6
    high: 1.0e-2
    log: true
  activation:
    type: categorical
    choices: ["ReLU", "LeakyReLU", "PReLU", "Tanh", "GELU", "Mish", "SiLU", "ELU"]

surrogates:
  - name: MultiONet
    batch_size: 65536
    epochs: 4096
    trials: 100
    optuna_params:
      branch_hidden_layers:
        type: int
        low: 1
        high: 6
      hidden_size:
        type: int
        low: 10
        high: 500
        step: 10
      output_factor:
        type: int
        low: 30
        high: 300
        step: 10
      trunk_hidden_layers:
        type: int
        low: 1
        high: 7
      beta:
        type: float
        low: 0.1
        high: 10.0
        log: true
      

  - name: FullyConnected
    batch_size: 65536
    epochs: 4096
    trials: 100
    optuna_params:
      hidden_size:
        type: int
        low: 10
        high: 500
        step: 10
      num_hidden_layers:
        type: int
        low: 1
        high: 6
      beta:
        type: float
        low: 0.1
        high: 10.0
        log: true

  - name: LatentPoly
    batch_size: 512
    epochs: 4096
    trials: 100
    optuna_params:
      degree:
        type: int
        low: 1
        high: 10
      latent_features:
        type: int
        low: 1
        high: 10
      coder_layers:
        type: int
        low: 1
        high: 6
      coder_width:
        type: int
        low: 10
        high: 600
        step: 100
      # coeff_network:
      #   type: categorical
      #   choices: ["True", "False"]
      # coeff_width:
      #   type: int
      #   low: 10
      #   high: 700
      #   step: 10
      # coeff_layers:
      #   type: int
      #   low: 1
      #   high: 5

  - name: LatentNeuralODE
    batch_size: 1024
    epochs: 4096
    trials: 200
    optuna_params:
      latent_features:
        type: int
        low: 1
        high: 15
      coder_layers:
        type: int
        low: 1
        high: 10
      coder_width:
        type: int
        low: 10
        high: 400
        step: 10
      ode_width:
        type: int
        low: 10
        high: 400
        step: 10
      ode_layers:
        type: int
        low: 1
        high: 10
      # encode_params:
      #   type: categorical
      #   choices: ["True", "False"]
